### ISSUE TITLE
偶然进来~

### ISSUE THREAD

**Issue by leiming** [zfengzhen/Blog#1]
一个偶然的机会逛进来

`《linux_programming_interface》读书笔记.md` 做得如此精美，赞叹不已~

请教：这篇精美的读书笔记是使用了 PPT 截图，还是说借助了一些其他 mind 类软件？

**Comment by zfengzhen** [comment]
感谢你的夸奖，我习惯采用visio工具去做这些读书笔记，通过图形化的东西去加深理解，图片就是visio另存为的图片。

发自我的 iPhone

**Comment by leiming** [comment]
@zfengzhen 原来如此，谢谢

**Comment by Akagi201** [comment]
怎么不弄个静态博客 @zfengzhen 
https://draw.io 也不错, xml格式的

**Comment by zfengzhen** [comment]
@Akagi201 之前用过hexo的静态博客，还是觉得麻烦，觉得这种形式比较简单一点，就懒得折腾了，习惯了
